### ISSUE TITLE
Kernel exception during boot

### ISSUE THREAD

**Issue by grunskis** [getsenic/senic-os#9] opened 2017-06-15 08:23 UTC
Attached `dmesg` output

[dmesg.txt](https://github.com/getsenic/senic-os/files/1077005/dmesg.txt)

System stays running

**Comment by larsblumberg** [comment] 2017-07-21 07:50
I got something very similar, the hub was running over night and this is the last output:

```
[13413.304719] Unable to handle kernel NULL pointer dereference at virtual address 00000040
[13413.312883] pgd = dee70000
[13413.315635] [00000040] *pgd=5e8fe835, *pte=00000000, *ppte=00000000
[13413.321926] Internal error: Oops: 17 [#1] SMP ARM
[13413.326623] Modules linked in: mt7601u mac80211 cfg80211
[13413.331941] CPU: 0 PID: 264 Comm: dbus-daemon Tainted: G        W       4.10.0 #1
[13413.339410] Hardware name: Allwinner sun8i Family
[13413.344106] task: df5caa00 task.stack: dedcc000
[13413.348640] PC is at unix_detach_fds+0x18/0x4c
[13413.353081] LR is at unix_stream_read_generic+0x788/0x82c
[13413.358473] pc : [<c05bc444>]    lr : [<c05bdd9c>]    psr: 200d0013
[13413.358473] sp : dedcdda8  ip : 00000010  fp : dedcde4c
[13413.369932] r10: ded66dfc  r9 : ded66c7c  r8 : 00000370
[13413.375150] r7 : 00000490  r6 : ded66c00  r5 : 00000000  r4 : deb2c900
[13413.381667] r3 : 00000040  r2 : 00000040  r1 : deb2c900  r0 : dedcddf8
[13413.388185] Flags: nzCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
[13413.395309] Control: 10c5387d  Table: 5ee7006a  DAC: 00000051
[13413.401046] Process dbus-daemon (pid: 264, stack limit = 0xdedcc210)
[13413.407390] Stack: (0xdedcdda8 to 0xdedce000)
[13413.411743] dda0:                   deb2c900 00000000 ded66c00 c05bdd9c 000000c3 000000c6
[13413.419911] ddc0: 000000d3 00000370 00000000 00000370 00000000 00000000 00000000 00000001
[13413.428078] dde0: df2c8780 ded66dc4 00000001 00000000 dedcc000 00000001 00000000 00000040
[13413.436245] de00: 00000000 00000000 00000000 0000004c df2c8780 c0341efc dedcde78 dedcde24
[13413.444413] de20: df5caa00 dedcdf6c 00000000 40000040 beabb8bc beabb848 dedcdeb8 df2c8780
[13413.452580] de40: beabb8fc c05bdf00 df5caa80 c05bc400 df2c8780 dedcdf6c 00000000 00000800
[13413.460747] de60: 40000040 00000000 dedcdeb8 c052dd78 00000000 00000000 000724d0 00000800
[13413.468913] de80: de93d280 de93d2b0 00000000 c052c82c deab038c dedcded8 00000000 dedcdf58
[13413.477080] dea0: de93d280 c022c77c 00000000 00000019 c0a03dc0 c022c704 de93d280 de93d2b0
[13413.485248] dec0: dedcded8 dedcdf58 00000000 00000000 de93d280 c022d2b8 dedcded8 dedcded8
[13413.493415] dee0: e0803000 00000040 beabb570 00000000 ded98300 ded98300 de93d280 00000000
[13413.501583] df00: dedcc000 c022e164 00000000 dffba640 dedcdf34 c013df38 00000000 dffba640
[13413.509750] df20: de93d2b0 0000e000 00000000 00000000 00000000 ded98300 beabb8bc 40000000
[13413.517918] df40: df2c8780 00000129 c0107644 dedcc000 00000000 c052ebc8 00000000 beabb570
[13413.526084] df60: 00000000 00000000 fffffff7 00000000 00000000 00000000 00000370 00000490
[13413.534252] df80: dedcde78 00000001 beabb848 0000004c 40000000 00000000 beabb914 000507c4
[13413.542419] dfa0: 00060d68 c0107480 beabb914 000507c4 0000000e beabb8bc 40000000 00000000
[13413.550587] dfc0: beabb914 000507c4 00060d68 00000129 0000004c beabb8bc 0000000e beabb8fc
[13413.558755] dfe0: b6f4ac18 beabb830 b6f30158 b6eb5318 600d0010 0000000e 00000000 00000000
[13413.566935] [<c05bc444>] (unix_detach_fds) from [<c05bdd9c>] (unix_stream_read_generic+0x788/0x82c)
[13413.575972] [<c05bdd9c>] (unix_stream_read_generic) from [<c05bdf00>] (unix_stream_recvmsg+0x3c/0x44)
[13413.585183] [<c05bdf00>] (unix_stream_recvmsg) from [<c052dd78>] (___sys_recvmsg+0x90/0x164)
[13413.593613] [<c052dd78>] (___sys_recvmsg) from [<c052ebc8>] (__sys_recvmsg+0x3c/0x68)
[13413.601438] [<c052ebc8>] (__sys_recvmsg) from [<c0107480>] (ret_fast_syscall+0x0/0x3c)
[13413.609349] Code: e5912024 e5802004 e5813024 e5903004 (e1d340f0)
[13413.615579] ---[ end trace 3de320e13c758dbd ]---
```

**Comment by TheMeaningfulEngineer** [comment] 2017-11-03 10:28
Duplicate of a closed issue. Closing.

**Closed by TheMeaningfulEngineer** 2017-11-03 10:28 UTC
